version: 0.0
os: linux

files:
  - source: scripts/
    destination: /home/ec2-user/scripts/

permissions:
  - object: /home/ec2-user/scripts/
    pattern: "*.sh"
    mode: 755
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root