version: '3.3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    environment:
      - MYSQL_DATABASE=kmail
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
