name: CI pipeline
on: [push, pull_request]
env:
  JAVA_VERSION: 21
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{env.JAVA_VERSION}}
    - name: Run checkstyle
      uses: dbelyaev/action-checkstyle@master
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        level: warning
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{env.JAVA_VERSION}}
    - name: Run Tests
      run: ./mvnw test
    - name: Display JUnit Test Results
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: "target/surefire-reports/*.xml"
        
