name: CI pipeline
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Install Checkstyle
      run: |
        curl -sL https://github.com/checkstyle/checkstyle/releases/latest/download/checkstyle-10.15.0-all.jar -o checkstyle.jar
    - name: Run Checkstyle
      run: java -jar checkstyle.jar -c /google_checks.xml src/ > checkstyle-report.txt || true
    - name: Display results in GitHub Actions
      uses: reviewdog/action-checkstyle@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        checkstyle_reporter_format: checkstyle
        fail_on_error: true
        level: error
        filter_mode: nofilter
          
    - name: Run Tests
      run: ./mvnw test
    - name: Display JUnit Test Results
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: "target/surefire-reports/*.xml"
        
